### ISSUE TITLE
Lowering minSdk API of the library

### ISSUE THREAD

**Issue by gilgoldzweig** [matpag/ClickDrawableTextView#2]
Use this function to check if device is rtl

private static final Set<String> RTL;

    static {
        Set<String> lang = new HashSet<>();
        lang.add("ar");
        lang.add("dv");
        lang.add("fa");
        lang.add("ha");
        lang.add("he");
        lang.add("iw");
        lang.add("ji");
        lang.add("ps");
        lang.add("ur");
        lang.add("yi");
        RTL = Collections.unmodifiableSet(lang);
    }

 public static boolean isRTL() {
        return RTL.contains(Locale.getDefault().getLanguage());
    }

    public static boolean isRTL(Locale locale) {
       return RTL.contains(locale.getLanguage());
    }

**Comment by matpag** [comment]
Prior to API 17, RTL support is not enabled.
I don't think hardcoding RTL locales changes the situation too much. There may be users that doesn't want RTL mode at all even in locales where the app should be in RTL.

A good approach could be performing RTL considerations only on API >= 17 (the user can choose using the `supportsRtl` flag in application manifest) and force LTR on API lower than 17

What do you think?
I've created a PR for this, you can take a look if you want

**Comment by matpag** [comment]
I will update the documentation and release a new version ASAP
